name: CI (staking bot pilot)
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check required files exist
        run: |
          test -d programs
          test -d tests
          test -f README.md
          test -f docs/OVERVIEW.md
          test -f docs/IDS.md
          test -f ops/RUNBOOK.md
